name: izii_app
description: iZiiApp - Community Marketplace & Smart Business Platform
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^17.2.3

  # Database
  drift: ^2.22.1
  sqlite3_flutter_libs: ^0.5.30
  sqlite3: ^2.4.6

  # Cache
  shared_preferences: ^2.3.4

  # Networking
  dio: ^5.7.0
  web_socket_channel: ^3.0.1

  # UI
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^1.2.0
  google_fonts: ^8.1.0

  # File & Media
  image_picker: ^1.1.2
  file_picker: ^11.0.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Auth & Security
  flutter_secure_storage: ^10.3.0

  # Location
  geolocator: ^14.0.2

  # Communication
  url_launcher: ^6.3.1
  share_plus: ^12.0.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  connectivity_plus: ^7.1.1
  collection: ^1.19.0
  google_generative_ai: ^0.4.6
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.2
  mobile_scanner: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.31.0
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  json_serializable: ^6.9.3
  freezed: ^3.2.5
  bloc_test: any
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

